# Generated by Django 6.0 on 2026-02-06 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='grammar_errors',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='essay',
            name='grammar_score',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='essay',
            name='spelling_errors',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
