# Generated by Django 6.0 on 2026-02-13 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competition', '0002_essay_grammar_errors_essay_grammar_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='essay',
            name='final_score',
            field=models.FloatField(default=0),
        ),
    ]
